from os.path import splitext
from .. import config

# Common image texture file name suffixes to be replaced
# Generated by ChatGPT

TEX_SUFFIX_ALIASES = {
    # base color
    "basecolor": config.get_setting("material_parameters.base_color", "BaseColor"),
    "base_color": config.get_setting("material_parameters.base_color", "BaseColor"),
    "albedo": config.get_setting("material_parameters.base_color", "BaseColor"),
    "diffuse": config.get_setting("material_parameters.base_color", "BaseColor"),
    "color": config.get_setting("material_parameters.base_color", "BaseColor"),
    "col": config.get_setting("material_parameters.base_color", "BaseColor"),
    "bc": config.get_setting("material_parameters.base_color", "BaseColor"),

    # ao
    "ao": config.get_setting("material_parameters.ambient_occlusion", "AmbientOcclusion"),
    "ambientocclusion": config.get_setting("material_parameters.ambient_occlusion", "AmbientOcclusion"),
    "ambient_occlusion": config.get_setting("material_parameters.ambient_occlusion", "AmbientOcclusion"),
    "occlusion": config.get_setting("material_parameters.ambient_occlusion", "AmbientOcclusion"),

    # roughness
    "roughness": config.get_setting("material_parameters.roughness", "Roughness"),
    "rough": config.get_setting("material_parameters.roughness", "Roughness"),
    "rgh": config.get_setting("material_parameters.roughness", "Roughness"),

    # metallic
    "metallic": config.get_setting("material_parameters.metallic", "Metallic"),
    "metal": config.get_setting("material_parameters.metallic", "Metallic"),
    "met": config.get_setting("material_parameters.metallic", "Metallic"),

    # normal
    "normal": config.get_setting("material_parameters.normal", "Normal"),
    "normals": config.get_setting("material_parameters.normal", "Normal"),
    "nrm": config.get_setting("material_parameters.normal", "Normal"),
    "nor": config.get_setting("material_parameters.normal", "Normal"),

    # height/displacement
    "height": config.get_setting("material_parameters.height", "Height"),
    "disp": config.get_setting("material_parameters.height", "Height"),
    "displacement": config.get_setting("material_parameters.height", "Height"),

    # opacity
    "opacity": config.get_setting("material_parameters.opacity", "Opacity"),
    "alpha": config.get_setting("material_parameters.opacity", "Opacity"),
    "transparency": config.get_setting("material_parameters.opacity", "Opacity"),
    "mask": config.get_setting("material_parameters.opacity", "Opacity"),

    # emissive
    "emissive": config.get_setting("material_parameters.emission_color", "EmissionColor"),
    "emission": config.get_setting("material_parameters.emission_color", "EmissionColor"),
    "emit": config.get_setting("material_parameters.emission_color", "EmissionColor"),
}

# Common file name prefixes to be replaces
# Generated by ChatGPT
KNOWN_PREFIXES = ("sm", "m", "t", "tex", "texture", "mat", "material", "mesh", "staticmesh", "static_mesh")


def validate_prefix(prefix: str, file_name: str) -> bool:
    """Returns True if file name contains prefix and False if not."""
    prefix_len: int = len(prefix)
    return prefix == file_name[:prefix_len]


def add_prefix_to_file(prefix: str, file_name: str) -> str:
    return prefix + file_name


def _strip_known_prefix(name: str, prefix: str) -> str:
    name_lower = name.lower()

    for prefix in KNOWN_PREFIXES:
        check = prefix + "_"
        if name_lower.startswith(check):
            return name[len(check):]

    return name


def normalize_texture_name(name: str) -> str:
    prefix: str = config.get_setting("naming_conventions.texture_prefix", "T_")
    base, ext = splitext(name)
    base = _strip_known_prefix(base, prefix)

    if "_" in base:
        parts = base.rsplit("_", 1)
        basename = parts[0]
        suffix = parts[1]
    else:
        basename = base
        suffix = None

    if suffix:
        normalized_suffix = TEX_SUFFIX_ALIASES.get(suffix.lower(), suffix)
        return f"{prefix}{basename}_{normalized_suffix}{ext}"
    else:
        return f"{prefix}{basename}{ext}"
