# Common image texture file name suffixes to be replaced
# Generated by ChatGPT
TEX_SUFFIX_ALIASES = {
    # base color
    "basecolor": "BaseColor",
    "base_color": "BaseColor",
    "albedo": "BaseColor",
    "diffuse": "BaseColor",
    "color": "BaseColor",
    "col": "BaseColor",
    "bc": "BaseColor",

    # ao
    "ao": "AmbientOcclusion",
    "ambientocclusion": "AmbientOcclusion",
    "ambient_occlusion": "AmbientOcclusion",
    "occlusion": "AmbientOcclusion",

    # roughness
    "roughness": "Roughness",
    "rough": "Roughness",
    "rgh": "Roughness",

    # metallic
    "metallic": "Metallic",
    "metal": "Metallic",
    "met": "Metallic",

    # normal
    "normal": "Normal",
    "normals": "Normal",
    "nrm": "Normal",
    "nor": "Normal",

    # height/displacement
    "height": "Height",
    "disp": "Height",
    "displacement": "Height",

    # opacity
    "opacity": "Opacity",
    "alpha": "Opacity",
    "transparency": "Opacity",
    "mask": "Opacity",

    # emissive
    "emissive": "Emissive",
    "emission": "Emissive",
    "emit": "Emissive",
}

# Common file name prefixes to be replaces
# Generated by ChatGPT
KNOWN_PREFIXES = ("sm", "m", "t", "tex", "texture", "mat", "material", "mesh", "staticmesh", "static_mesh")


def validate_prefix(prefix: str, file_name: str) -> bool:
    """Returns True if file name contains prefix and False if not."""
    prefix_len: int = len(prefix)
    return prefix == file_name[:prefix_len]


def add_prefix_to_file(prefix: str, file_name: str) -> str:
    return prefix + file_name


def normalize_file_name(prefix: str, suffix: str | None, file_name: str) -> str:
    return "TODO finish"